### ISSUE TITLE
Support months always having six weeks.

### ISSUE THREAD

**Issue by ztcollazo** [maggialejandro/react-native-month#65]
Hey, I'm creating a Calendar component for one of my apps (Expo + Next.js), and I'm using `react-native-month` to render the months. I ran into a bit of an issue (not necessarily) with switching between months with a different number of weeks. This year, May has six weeks but June has five, just as an example. And some rare years, February only has four weeks. `react-native-calendars` supports a `showSixWeeks` prop, so I was wondering if the same thing could be done with `react-native-month`.

**Comment by ztcollazo** [comment]
@maggialejandro I have it ready, can I open a PR for this?

**Comment by maggialejandro** [comment]
@ztcollazo Yeah! sure!

**Comment by ztcollazo** [comment]
@maggialejandro It's ready for review when you're available.
