### ISSUE TITLE
Show week numbers

### ISSUE THREAD

**Issue by TNAJanssen** [maggialejandro/react-native-month#86]
### Current behaviour

It's showing a month without week numbers.

### Expected behaviour

Allow to also show week numbers

### Code sample

Not applicable

### Screenshots (if applicable)

Not applicable

### What have you tried

I'm creating a merge request.

### Your Environment

Not applicable

**Comment by maggialejandro** [comment]
Sorry for the delay. If what you mean is displaying the week number relative to the year, that feature hasn't been implemented. I'll close the issue; feel free to create a new one or submit a PR.
